{% set data = load_setup_py_data() %}

package:
  name: albumentationsx
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools

  build:
    - python
    - numpy>=2.2.6
    - scipy
    - pydantic>=2.9
    - pytorch
    - typing_extensions
    - opencv-python-headless

  run:
    - python
    - numpy>=2.2.6
    - scipy>=1.15.3
    - pyyaml
    - pydantic>=2.12.4
    - typing-extensions>=4.9.0
    - opencv-python-headless>=5.0.0.93
    - albucore==0.2.5
    - numkong!=7.7.1

suggests:
  - pytorch
  - huggingface-hub
  - pillow

test:
  imports:
    - albumentations

about:
  home: {{ data['url'] }}
  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - LICENSE
    - LICENSING.md
    - THIRD_PARTY_NOTICES.md
    - THIRD_PARTY_LICENSES/MIT-Albumentations-2.0.8.txt
  summary: {{ data['description'] }}
